// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwZQzHYtpvchNcyzSlLFhIRVPNGY6JnM',
    appId: '1:295636561358:web:14938fead06c2a763acf9f',
    messagingSenderId: '295636561358',
    projectId: 'simbureum-80683',
    authDomain: 'simbureum-80683.firebaseapp.com',
    storageBucket: 'simbureum-80683.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7Li0uwGGEqoM4ggSw9FObRMqlEsigpo',
    appId: '1:295636561358:android:766f94165e2366183acf9f',
    messagingSenderId: '295636561358',
    projectId: 'simbureum-80683',
    storageBucket: 'simbureum-80683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNrW0x7u30ac7B7MulIUAIEsqAx9Z9_oo',
    appId: '1:295636561358:ios:b3e2f0f794063c8c3acf9f',
    messagingSenderId: '295636561358',
    projectId: 'simbureum-80683',
    storageBucket: 'simbureum-80683.appspot.com',
    iosBundleId: 'com.example.flutterNewbieProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNrW0x7u30ac7B7MulIUAIEsqAx9Z9_oo',
    appId: '1:295636561358:ios:629cfc1fce173a7e3acf9f',
    messagingSenderId: '295636561358',
    projectId: 'simbureum-80683',
    storageBucket: 'simbureum-80683.appspot.com',
    iosBundleId: 'com.example.flutterNewbieProject.RunnerTests',
  );
}
